/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.engine;

import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import org.itson.player.Player;
import org.itson.room.RoomController;

/**
 *
 * @author arace
 */
public class FrmCreateRoom extends javax.swing.JFrame {

    private static FrmCreateRoom instance;
    
    private RoomController roomController;
    private int numberOfPlayers;
    
    private Player player;

    /**
     * Creates new form FrmCreateRoom
     */
    private FrmCreateRoom() {
        roomController = RoomController.get();
        initComponents();
    }
    
    private void showFrmMainMenuPlayer() {
        int option = JOptionPane.showConfirmDialog(this, "Do you want to come back?", "Exit", JOptionPane.YES_NO_OPTION);
        
        if (option == JOptionPane.YES_OPTION) {
            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            FrmMainMenuPlayer.get().setVisible(true);
            this.dispose();
        } else {
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }
    }
    
    private void showFrmRoom() {
        FrmRoom frmRoom = FrmRoom.get();
        
        roomController.createRoom(numberOfPlayers);
        frmRoom.setRoom(this.roomController.getRoom());
        frmRoom.setMaxNumberOfPlayers(this.numberOfPlayers);
        frmRoom.setPlayer(this.player);
        frmRoom.addPlayer(this.player);
        this.hiddenWindow();
        frmRoom.setVisible(true);
    }
    
    private void hiddenWindow() {
        setVisible(false);
    }
    
    private void choiceNumberOfPlayers(int value) {
        this.numberOfPlayers = value;
    }
    
    public void setPlayer(Player player) {
        this.player = player;
    }

    public static FrmCreateRoom get() {
        if (FrmCreateRoom.instance == null) {
            FrmCreateRoom.instance = new FrmCreateRoom();
        }
        
        return FrmCreateRoom.instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        checkTwoPlayers = new javax.swing.JCheckBox();
        checkThreePlayers = new javax.swing.JCheckBox();
        checkFourPlayers = new javax.swing.JCheckBox();
        btnCreateRoom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel1.setText("Configurar sala");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 34, -1, -1));

        btnExit.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 359, -1, -1));

        btnHelp.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnHelp.setText("Help");
        jPanel1.add(btnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 359, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setText("Seleccione cantidad de jugadores");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 75, -1, -1));

        checkTwoPlayers.setForeground(new java.awt.Color(0, 0, 0));
        checkTwoPlayers.setText("2");
        checkTwoPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTwoPlayersActionPerformed(evt);
            }
        });
        jPanel1.add(checkTwoPlayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 120, 220));

        checkThreePlayers.setForeground(new java.awt.Color(0, 0, 0));
        checkThreePlayers.setText("3");
        checkThreePlayers.setToolTipText("");
        checkThreePlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkThreePlayersActionPerformed(evt);
            }
        });
        jPanel1.add(checkThreePlayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 110, 240));

        checkFourPlayers.setForeground(new java.awt.Color(0, 0, 0));
        checkFourPlayers.setText("                       4");
        checkFourPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFourPlayersActionPerformed(evt);
            }
        });
        jPanel1.add(checkFourPlayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 109, 270));

        btnCreateRoom.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnCreateRoom.setText("Crear sala");
        btnCreateRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateRoomActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreateRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 346, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateRoomActionPerformed
        this.showFrmRoom();
    }//GEN-LAST:event_btnCreateRoomActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.showFrmMainMenuPlayer();
    }//GEN-LAST:event_btnExitActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.showFrmMainMenuPlayer();
    }//GEN-LAST:event_formWindowClosing

    private void checkThreePlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkThreePlayersActionPerformed
        checkTwoPlayers.setSelected(false);
        checkFourPlayers.setSelected(false);
        this.choiceNumberOfPlayers(Integer.parseInt(this.checkThreePlayers.getText()));
    }//GEN-LAST:event_checkThreePlayersActionPerformed

    private void checkFourPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFourPlayersActionPerformed
        checkTwoPlayers.setSelected(false);
        checkThreePlayers.setSelected(false);
        this.choiceNumberOfPlayers(Integer.parseInt(this.checkFourPlayers.getText()));
    }//GEN-LAST:event_checkFourPlayersActionPerformed

    private void checkTwoPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTwoPlayersActionPerformed
        checkThreePlayers.setSelected(false);
        checkFourPlayers.setSelected(false);
        choiceNumberOfPlayers(Integer.parseInt(this.checkTwoPlayers.getText()));
    }//GEN-LAST:event_checkTwoPlayersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCreateRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCreateRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCreateRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCreateRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCreateRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateRoom;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHelp;
    private javax.swing.JCheckBox checkFourPlayers;
    private javax.swing.JCheckBox checkThreePlayers;
    private javax.swing.JCheckBox checkTwoPlayers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
