/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.engine;

import org.itson.game.GameView;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.itson.player.Player;

/**
 *
 * @author arace
 */
public class FrmMainMenuPlayer extends javax.swing.JFrame {

    private static FrmMainMenuPlayer instance;
    
    private Player player;

    /**
     * Creates new form MainMenuPlayer
     */
    private FrmMainMenuPlayer() {      
        initComponents();
    }
    
    private void showFrmMainMenu() {
        int option = JOptionPane.showConfirmDialog(this, "Do you want to come back?", "Exit", JOptionPane.YES_NO_OPTION);
        
        if (option == JOptionPane.YES_OPTION) {
            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            FrmMainMenu.get().setVisible(true);
            this.dispose();
        } else {
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }
    }
    
    private void hiddenWindow() {
        setVisible(false);
    }
    
    private void showFrmCreateRoom() {
        FrmCreateRoom frmCreateRoom = FrmCreateRoom.get();
        frmCreateRoom.setPlayer(player);
        frmCreateRoom.setVisible(true);
        hiddenWindow();
    }
    private void showFrmGame() throws IOException{
        GameView frmGame = GameView.get();
        frmGame.setVisible(true);
        hiddenWindow();
    }
    public void setPlayer(Player player) {
        get().player = player;
        setPlayerName(get().player);
    }
    
    private void setPlayerName(Player player) {
        lblName.setText(player.getName());
    }

    public static FrmMainMenuPlayer get() {
        if (FrmMainMenuPlayer.instance == null) {
            FrmMainMenuPlayer.instance = new FrmMainMenuPlayer();

        }
        return FrmMainMenuPlayer.instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRoom = new javax.swing.JButton();
        btnCreateRoom = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblPlayer = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblBakcround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRoom.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/other/btnjoingame.png"))); // NOI18N
        btnRoom.setBorderPainted(false);
        btnRoom.setContentAreaFilled(false);
        btnRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomActionPerformed(evt);
            }
        });
        getContentPane().add(btnRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 90, -1));

        btnCreateRoom.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnCreateRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/other/creaR0m.png"))); // NOI18N
        btnCreateRoom.setBorderPainted(false);
        btnCreateRoom.setContentAreaFilled(false);
        btnCreateRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateRoomActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreateRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 90, 40));

        btnHelp.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/other/help.png"))); // NOI18N
        btnHelp.setBorderPainted(false);
        btnHelp.setContentAreaFilled(false);
        getContentPane().add(btnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, -1, -1));

        btnExit.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/other/Boton.png"))); // NOI18N
        btnExit.setContentAreaFilled(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        lblPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/other/player.png"))); // NOI18N
        getContentPane().add(lblPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        lblName.setBackground(new java.awt.Color(255, 255, 255));
        lblName.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 180, 40));

        lblBakcround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/other/frmMainMenuPlayer (1).png"))); // NOI18N
        getContentPane().add(lblBakcround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateRoomActionPerformed
        showFrmCreateRoom();
    }//GEN-LAST:event_btnCreateRoomActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        showFrmMainMenu();
    }//GEN-LAST:event_formWindowClosing

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        showFrmMainMenu();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomActionPerformed
        try {
            showFrmGame();
        } catch (IOException ex) {
            Logger.getLogger(FrmMainMenuPlayer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRoomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMainMenuPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMainMenuPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMainMenuPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMainMenuPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMainMenuPlayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateRoom;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnRoom;
    private javax.swing.JLabel lblBakcround;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPlayer;
    // End of variables declaration//GEN-END:variables
}
