package org.itson.game;

import java.io.IOException;
import java.util.List;
import javax.swing.JOptionPane;
import org.itson.engine.FrmMainMenu;
import static org.itson.engine.ModelFactory.getPlayer;
import org.itson.player.Player;
import org.itson.token.TokenComponent;
import org.itson.token.TokenManager;
import org.itson.token.TokenView;

/**
 *
 * @author oscar
 */
public class GameView extends javax.swing.JFrame {

    private GameController gameController;
    private static GameView instance;
    public TokenManager tokenManager;
    /**
     * Creates new form FrmGame
     */
    private GameView() throws IOException {
        this.tokenManager = TokenManager.get();
        initComponents();
    }

    public static GameView get() throws IOException {
        if (GameView.instance == null) {
            GameView.instance = new GameView();
        }

        return GameView.instance;
    }

    private void showFrmGame() {
        int option = JOptionPane.showConfirmDialog(this, "Do you want to come back?", "Exit", JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION) {
            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            FrmMainMenu.get().setVisible(true);
            this.dispose();
        } else {
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }
    }

    public void setPlayer(Player player) {
        setPlayerName(player);
    }

    private void setPlayerName(Player player) {
        lblNamePlayer1.setText(player.getName());

    }

//    public void setGameController(GameController gameController) {
//        this.gameController = gameController;
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPlayer1 = new javax.swing.JLabel();
        lblPlayer2 = new javax.swing.JLabel();
        lblPlayer3 = new javax.swing.JLabel();
        lblPlayer4 = new javax.swing.JLabel();
        lblNamePlayer1 = new javax.swing.JLabel();
        lblNamePlayer3 = new javax.swing.JLabel();
        lblNamePlayer2 = new javax.swing.JLabel();
        lblNamePlayer4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lblPlayer1.setText("Player 1: ");
        lblPlayer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPlayer1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblPlayer1MousePressed(evt);
            }
        });

        lblPlayer2.setText("Player 2: ");

        lblPlayer3.setText("Player 3: ");
        lblPlayer3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPlayer3MouseClicked(evt);
            }
        });

        lblPlayer4.setText("Player 4: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblPlayer4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNamePlayer4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPlayer2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNamePlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPlayer1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNamePlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPlayer3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNamePlayer3)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlayer3)
                    .addComponent(lblNamePlayer3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNamePlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPlayer2)
                        .addComponent(lblPlayer4)
                        .addComponent(lblNamePlayer4)))
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlayer1)
                    .addComponent(lblNamePlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        TokenView tokenView = this.tokenManager.getRandomTokenView();
        if (tokenView != null) {
            // Obtiene las coordenadas actuales del mouse en relación con el formulario
            int newX = evt.getX();
            int newY = evt.getY();

            // Establece la ubicación de la ficha en las nuevas coordenadas
            tokenView.setLocation(newX, newY);

            // Agrega la ficha al formulario
            this.add(tokenView);

            // Vuelve a pintar el formulario
            this.repaint();
        }
    }//GEN-LAST:event_formMouseClicked

    private void lblPlayer1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPlayer1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPlayer1MousePressed

    private void lblPlayer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPlayer1MouseClicked

    }//GEN-LAST:event_lblPlayer1MouseClicked

    private void lblPlayer3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPlayer3MouseClicked

    }//GEN-LAST:event_lblPlayer3MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) throws IOException {
//        Game game = new Game();
//        TokenManager tokenManager = new TokenManager();
//        GameView gameView = new GameView();
//        GameController gameController = new GameController();
//        gameView.setGameController(gameController);
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                try {
//                    new GameView().setVisible(true);
//                } catch (IOException ex) {
//                    Logger.getLogger(GameView.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblNamePlayer1;
    private javax.swing.JLabel lblNamePlayer2;
    private javax.swing.JLabel lblNamePlayer3;
    private javax.swing.JLabel lblNamePlayer4;
    private javax.swing.JLabel lblPlayer1;
    private javax.swing.JLabel lblPlayer2;
    private javax.swing.JLabel lblPlayer3;
    private javax.swing.JLabel lblPlayer4;
    // End of variables declaration//GEN-END:variables
}
